[workspace]
members = ["ms56xx", "ms5607", "ms5611", "ms5637"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Louis Schell <louis.schell1@gmx.de>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Rechenmaschine/ms5607"
keywords = ["embedded", "no-std", "embedded-hal", "sensor", "async"]
categories = ["embedded", "no-std"]

[workspace.dependencies]
embedded-hal-async = "1.0.0"
embedded-hal = "1.0.0"
defmt = "1.0.1"
