[workspace]
members = ["ms56xx", "ms5607-rs", "ms5611-rs", "ms5637-rs"]
resolver = "2"

[workspace.package]
edition = "2024"
authors = ["Louis Schell <louis.schell1@gmx.de>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Rechenmaschine/ms56xx"
keywords = ["embedded", "no-std", "embedded-hal", "sensor", "async"]
categories = ["embedded", "no-std"]

[workspace.dependencies]
embedded-hal-async = "1.0.0"
embedded-hal = "1.0.0"
defmt = "1.0.1"
